name: build node.js project.

on: 
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: install dependencies.
        run: npm install