name: build node.js project.

on: 
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies.
        run: npm install
      - name: compressing node modules.
        run: tar Jcvf node_modules.tar.gz node_modules
      - name: upload modules stuff.
        uses: actions/upload-artifact@v3
        with:
          name: modules
          path: app/node_modules.tar.gz