name: build node.js project.

on: 
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app/
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies.
        run: npm install